### ISSUE TITLE
'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by endy-see** [clovaai/assembled-cnn#3]
I want use assembled-cnn to finetune my own dataset, with script as:
![image](https://user-images.githubusercontent.com/13143336/78733578-6a057380-7978-11ea-9d02-f473a0a931ec.png)

but run error as follows:
2020-04-07 13:49:57.225 I: Running local_init_op.
2020-04-07 13:49:57.382 I: Done running local_init_op.
2020-04-07 13:49:59.904892: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-04-07 13:50:00.878725: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-04-07 13:50:14.567 I: Finished evaluation at 2020-04-07-13:50:14
2020-04-07 13:50:14.568 I: Saving dict for global step 0: accuracy = 0.005, accuracy_top_5 = 0.024, ece = 0.99431515, global_step = 0, loss = 94.326965
---->>>>>>> current_ckpt= /home/zhaoyanmei/projects/assembled-cnn/models/
2020-04-07 13:50:15.498 W: From /home/zhaoyanmei/projects/assembled-cnn/utils/checkpoint_utils.py:72: The name tf.gfile.IsDirectory is deprecated. Please use tf.io.gfile.isdir instead.

Traceback (most recent call last):
  File "main_classification.py", line 64, in <module>
    absl_app.run(main)
  File "/root/miniconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main_classification.py", line 58, in main
    run(flags.FLAGS)
  File "main_classification.py", line 54, in run
    num_images=dataset.num_images, zeroshot_eval=flags_obj.zeroshot_eval)
  File "/home/zhaoyanmei/projects/assembled-cnn/nets/run_loop_classification.py", line 480, in resnet_main
    ckpt_keeper.save(metric, flags_obj.model_dir)
  File "/home/zhaoyanmei/projects/assembled-cnn/utils/checkpoint_utils.py", line 75, in save
    if current_ckpt.startswith('hdfs'):
AttributeError: 'NoneType' object has no attribute 'startswith'

Can some know what's this problems?

**Comment by sweaterr** [comment]
Hi. It seems that output path is `None` because the checkpoint in `MODEL_DIR` was not found. Check if the output path `MODEL_DIR` is empty. MODEL_DIR directory should be not exist unless you are resuming a previously learned model

**Comment by endy-see** [comment]
> Hi. It seems that output path is `None` because the checkpoint in `MODEL_DIR` was not found. Check if the output path `MODEL_DIR` is empty. MODEL_DIR directory should be not exist unless you are resuming a previously learned model

Hi, as your suggestion, I adjust my running script, set MODEL_DIR to an empty path and PRETRAINED_PATH to Assemble-ResNet50 path, and it runs. But another problem occured as follow: 

2020-04-08 01:13:57.344 I: resnet_model/stage4/batch_normalization_9/gamma:0
2020-04-08 01:13:57.344 I: resnet_model/stage4/batch_normalization_9/beta:0
2020-04-08 01:13:57.344 I: *********** end   var_list_warm_start **************
2020-04-08 01:13:57.344 I: Fine-tuning from /home/zhaoyanmei/projects/assembled-cnn/pretrain/Assemble-ResNet50/model.ckpt-754895
2020-04-08 01:13:57.345 W: From /root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2020-04-08 01:13:57.350 I: Restoring parameters from /home/zhaoyanmei/projects/assembled-cnn/pretrain/Assemble-ResNet50/model.ckpt-754895
2020-04-08 01:15:34.089019: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-04-08 01:15:37.713545: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid JPEG data, size 175575
	 [[{{node ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
  (1) Invalid argument: Invalid JPEG data, size 175575
	 [[{{node ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
	 [[Momentum/update_2_306/update/_23704]]
0 successful operations.
3 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_classification.py", line 64, in <module>
    absl_app.run(main)
  File "/root/miniconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main_classification.py", line 58, in main
    run(flags.FLAGS)
  File "main_classification.py", line 54, in run
    num_images=dataset.num_images, zeroshot_eval=flags_obj.zeroshot_eval)
  File "/home/zhaoyanmei/projects/assembled-cnn/nets/run_loop_classification.py", line 475, in resnet_main
    eval_results = train_and_evaluate(train_hooks)
  File "/home/zhaoyanmei/projects/assembled-cnn/nets/run_loop_classification.py", line 435, in train_and_evaluate
    steps=flags_obj.max_train_steps)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1156, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1219, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1329, in _actual_train_model_distributed
    saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1484, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid JPEG data, size 175575
	 [[{{node ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
  (1) Invalid argument: Invalid JPEG data, size 175575
	 [[{{node ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
	 [[Momentum/update_2_306/update/_23704]]
0 successful operations.
3 derived errors ignored.
[root@d9fc0866d3c9 assembled-cnn]#

I suspect it's a data problem, but I don't know how to check it. My dataset is a bird classification dataset, it's label only contains a class number, I deal it as datasets/build_fgvc_aircraft.py to convert to tfrecord, now it seems not work

**Comment by sweaterr** [comment]
> Not a JPEG file: starts with 0x89 0x50

It seems that the image is not a valid jpg format file. Seems like you need to check if your data is jpg data?

**Comment by endy-see** [comment]
> > Not a JPEG file: starts with 0x89 0x50
> 
> It seems that the image is not a valid jpg format file. Seems like you need to check if your data is jpg data?

yes，you are right, I check the mode of images, then convert them to jpg, then problem solved. Thank you for your patience！
