### ISSUE TITLE
Finetune with Assemble-ResNet152, but failed

### ISSUE THREAD

**Issue by endy-see** [clovaai/assembled-cnn#4]
Hi, I can finetune with Assemble-ResNet50, but when I try with  Assemble-ResNet152, errors occured as follow：

2020-04-09 00:59:00.514 I: resnet_model/stage4/batch_normalization_9/gamma:0
2020-04-09 00:59:00.514 I: resnet_model/stage4/batch_normalization_9/beta:0
2020-04-09 00:59:00.514 I: *********** end   var_list_warm_start **************
2020-04-09 00:59:00.514 I: Fine-tuning from /data/zhaoyanmei/projects/assembled-cnn/pretrain/Assemble-ResNet152/model.ckpt-750683
2020-04-09 00:59:00.514 W: From /root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2020-04-09 00:59:00.520 I: Restoring parameters from /data/zhaoyanmei/projects/assembled-cnn/pretrain/Assemble-ResNet152/model.ckpt-750683
2020-04-09 01:04:37.134675: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-04-09 01:04:43.513984: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [32] vs. [64]
	 [[{{node replica_2/resnet_model/stage0/pool/batch_normalization_1/AssignMovingAvg_1/sub_1}}]]
  (1) Invalid argument: Incompatible shapes: [32] vs. [64]
	 [[{{node replica_2/resnet_model/stage0/pool/batch_normalization_1/AssignMovingAvg_1/sub_1}}]]
	 [[Momentum/update_3_826/update/_64128]]
0 successful operations.
3 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_classification.py", line 64, in <module>
    absl_app.run(main)
  File "/root/miniconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main_classification.py", line 58, in main
    run(flags.FLAGS)
  File "main_classification.py", line 54, in run
    num_images=dataset.num_images, zeroshot_eval=flags_obj.zeroshot_eval)
  File "/data/zhaoyanmei/projects/assembled-cnn/nets/run_loop_classification.py", line 475, in resnet_main
    eval_results = train_and_evaluate(train_hooks)
  File "/data/zhaoyanmei/projects/assembled-cnn/nets/run_loop_classification.py", line 435, in train_and_evaluate
    steps=flags_obj.max_train_steps)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1156, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1219, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1329, in _actual_train_model_distributed
    saving_listeners)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1484, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [32] vs. [64]
	 [[node replica_2/resnet_model/stage0/pool/batch_normalization_1/AssignMovingAvg_1/sub_1 (defined at data/zhaoyanmei/projects/assembled-cnn/nets/model_helper.py:37) ]]
  (1) Invalid argument: Incompatible shapes: [32] vs. [64]
	 [[node replica_2/resnet_model/stage0/pool/batch_normalization_1/AssignMovingAvg_1/sub_1 (defined at data/zhaoyanmei/projects/assembled-cnn/nets/model_helper.py:37) ]]
	 [[Momentum/update_3_826/update/_64128]]
0 successful operations.
3 derived errors ignored.

Original stack trace for 'replica_2/resnet_model/stage0/pool/batch_normalization_1/AssignMovingAvg_1/sub_1':
  File "root/miniconda3/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "root/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 911, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "data/zhaoyanmei/projects/assembled-cnn/functions/model_fns.py", line 239, in model_fn_cls
    p=params)
  File "data/zhaoyanmei/projects/assembled-cnn/nets/run_loop_classification.py", line 122, in resnet_model_fn
    use_resnet_d=p['use_resnet_d'], keep_prob=keep_prob)
  File "data/zhaoyanmei/projects/assembled-cnn/nets/resnet_model.py", line 402, in __call__
    little0 = batch_norm(little0, training, self.data_format, momentum=self.bn_momentum)
  File "data/zhaoyanmei/projects/assembled-cnn/nets/model_helper.py", line 37, in batch_norm
    scale=True, training=training, fused=True, gamma_initializer=gamma_initializer, name=name)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 327, in batch_normalization
    return layer.apply(inputs, training=training)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 446, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 253, in _call_unconverted
    return f(*args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 167, in call
    return super(BatchNormalization, self).call(inputs, training=training)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 651, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 534, in _fused_batch_norm
    self.add_update(variance_update, inputs=True)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1082, in add_update
    updates = [process_update(x) for x in updates]
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1082, in <listcomp>
    updates = [process_update(x) for x in updates]
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1070, in process_update
    return update()
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1066, in <lambda>
    update = lambda: process_update(x())
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 531, in variance_update
    momentum, inputs_size)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 454, in _assign_moving_average
    variable - math_ops.cast(value, variable.dtype)) * decay
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/distribute/values.py", line 386, in __sub__
    def __sub__(self, o): return self.get() - o
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1045, in _run_op
    return tensor_oper(a.value(), *args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10855, in sub
    "Sub", x=x, y=y, name=name)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

[root@ca6c7b6992e6 assembled-cnn]#

Is there any param I need to adjust?

**Comment by sweaterr** [comment]
Hi,
In run script, the option params related to network tweak (except anti-alias because it has no trainable parameters )should be matched to pretrained params

```
CUDA_VISIBLE_DEVICES=0,1,2,3 python main_classification.py \
--dataset_name=food101 \
--data_dir=${DATA_DIR} \
--model_dir=${MODEL_DIR} \
--pretrained_model_checkpoint_path=${PRETRAINED_PATH} \
--num_gpus=4 \
--mixup_type=1 \
--autoaugment_type=good \
--label_smoothing=0.1 \
--resnet_version=2 \ # this is should be set
--resnet_size=50 \
--anti_alias_filter_size=3 \ 
--anti_alias_type=sconv \ 
--use_sk_block=True \ # this is should be set
--use_dropblock=True \
--dropblock_kp="0.9,0.7" \
--batch_size=256 \
--base_learning_rate=0.01 \
--learning_rate_decay_type=cosine \
--lr_warmup_epochs=5 \
--train_epochs=100 \
--bn_momentum=0.966 \
--weight_decay=0.001 \
--keep_checkpoint_max=0 \
--ratio_fine_eval=0.9 \
--epochs_between_evals=10 \
--clean

```

In addition, in case of Assemble-ResNet152, additional parameter should be set

```
--bl_alpha=1 \
--bl_beta=2 \
```

Thanks for reporting :)

**Comment by endy-see** [comment]
> --bl_alpha=1 \
> --bl_beta=2 \

Yes ,after add --bl_alpha=1 and --bl_beta=2, finetune with Assemble-ResNet152 works 
my script as follows:

CUDA_VISIBLE_DEVICES=0,1 python main_classification.py \
--dataset_name=ssfgrc \
--data_dir=${DATA_DIR} \
--model_dir=${MODEL_DIR} \
--pretrained_model_checkpoint_path=${PRETRAINED_PATH} \
--num_gpus=2 \
--mixup_type=1 \
--autoaugment_type=imagenet \
--label_smoothing=0.1 \
--resnet_version=2 \
--resnet_size=152 \
--anti_alias_filter_size=3 \
--anti_alias_type=sconv \
--use_sk_block=True \
--use_dropblock=True \
--dropblock_kp="0.9,0.7" \
--batch_size=64 \
--base_learning_rate=0.005 \
--learning_rate_decay_type=cosine \
--lr_warmup_epochs=5 \
--train_epochs=100 \
--bn_momentum=0.966 \
--weight_decay=0.001 \
--keep_checkpoint_max=0 \
--ratio_fine_eval=0.9 \
--epochs_between_evals=10 \
--bl_alpha=1 \
--bl_beta=2 \
--clean

thank you for your patience
